### PR TITLE
Refactoring

### PR DESCRIPTION
**Pull request by maichmueller**
Hi Simon,

In this PR I...
 - refactored some of the cmake structure into smaller parts that define their own targets
 - refactored the cmake targets for mimir, pymimir (and changed some install settings too)
 - introduced link time optimization, sanitizer, and other compile time flags that are typically recommended
 - introduced the recommended set of compiler warnings (currently, this vomits out quite a lot of warnings due to e.g. name shadowing among other things which can be addressed later)
 - removed gitsubmodules
 - moved (more) dependencies to conan (pybind11)
 - added a configure.sh and build.sh script to configure and build via terminal easily (configure.sh --conan && build.sh)
 - moved some of setup.py's metadata to pyproject.toml
- changed c++17 to c++20 (would enable e.g. ranges lib)

### CODE REVIEW

**Comment by simon-stahlberg** [comment]
Hi Michael,

Currently, @drexlerd and I are undertaking a significant refactoring of this repository. We plan to integrate Loki, which can be found at [https://github.com/drexlerd/Loki](https://github.com/drexlerd/Loki), as the PDDL parser for this project. Concurrently, we are reorganizing all the CMake files and our approach to managing dependencies. In the loki-branch, dependencies are managed using `ExternalProject_Add` rather than submodules, `add_subdirectory`, or system dependencies. We are quite happy with this method as it avoids introducing any additional dependencies, such as Python and Conan, in your case.

While I am generally open to merging this, it's important to note that it will be superseded by the loki-branch once it is completed. Since we are refactoring and rewriting code, if you have any feedback regarding the code's actual design, including design patterns and similar aspects, now would be a good time to schedule a meeting and discuss.

/Simon

**Comment by drexlerd** [comment]
@maichmueller the branch we are currently working on is the `templated-design` where the another goal is to use static polymorphism instead of runtime polymorphism where it is not needed to additionally get the compiler on our sides.

**Comment by maichmueller** [comment]
Hi all,

ok i did not know that there are such advanced plans in order. happy to see there is movement! 

From a quick glance at the branch I think there are parts of this PR that might be still relevant for the ongoing efforts and aspects that I could contribute to. I am happy to schedule a meeting on this and discuss. We can then also see whether to merge this PR now or postpone/close/revisit again at a later stage.

**Comment by simon-stahlberg** [comment]
I decided to backport the CMake solution in the loki branch, which conflicts with these changes. I'll close this PR for now, and we can revisit the topic later.

**Pull request closed without merging**
